### ISSUE TITLE
Especificação de necessidade de deslocamento para interação entre equipes

### ISSUE THREAD

**Issue by mjlelis** [uira/SistemaDeCompras#8]
No Documento, "TDR - Consultoria para Gestão de Compras em Rede - Documentos Google.pdf" página 11, item 8.1, é importante especificar a eventual necessidade de deslocamento para interação entre equipe de Estados distintos, e quais as implicações e responsabilidades de custos para as partes.

Mauricio Lelis
Coordenação de Desenvolvimento de Negócios
Avansys Tecnologia LTDA.
CNPJ: 04.181.950/0001-10
Cel. 71 99238-5072
Tel. (71) 3617-0707
AV LUIZ TARQUINIO, 2580, SALA 302 QUADRAB000 LOTE 0003A LOT GRJ REUN CONC, PITANGUEIRAS, LAURO DE FREITAS/BA
CEP - 42.700-000

**Comment by mjlelis** [comment]
No Documento, "TDR - Consultoria para Gestão de Compras em Rede - Documentos Google.pdf" página 6, item 4.4 (Design Thinking), por se tratar de uma processo que requer enorme troca e interação entre os envolvidos, é importante especificar a eventual necessidade de deslocamento (ou não) para interação entre equipe de Estados distintos, e quais as implicações e responsabilidades de custos para as partes.

Mauricio Lelis
Coordenação de Desenvolvimento de Negócios
Avansys Tecnologia LTDA.
CNPJ: 04.181.950/0001-10
Cel. 71 99238-5072
Tel. (71) 3617-0707
AV LUIZ TARQUINIO, 2580, SALA 302 QUADRAB000 LOTE 0003A LOT GRJ REUN CONC, PITANGUEIRAS, LAURO DE FREITAS/BA
CEP - 42.700-000

**Comment by mjlelis** [comment]
No Documento, "TDR - Consultoria para Gestão de Compras em Rede - Documentos Google.pdf" página 9, item 5.2 "Repasse tecnológico, capacitação e colaboração em rede", por se tratar de transferência de conhecimento, é importante especificar a eventual necessidade de deslocamento (ou não) para interação entre equipe de Estados distintos, e quais as implicações e responsabilidades de custos para as partes.

Mauricio Lelis
Coordenação de Desenvolvimento de Negócios
Avansys Tecnologia LTDA.
CNPJ: 04.181.950/0001-10
Cel. 71 99238-5072
Tel. (71) 3617-0707
AV LUIZ TARQUINIO, 2580, SALA 302 QUADRAB000 LOTE 0003A LOT GRJ REUN CONC, PITANGUEIRAS, LAURO DE FREITAS/BA
CEP - 42.700-000

**Comment by mjlelis** [comment]
Diferente do que consta no "TDR - Consultoria para Gestão de Compras em Rede - Documentos Google.pdf", o arquivo "Anexo 03 - Requisitos - Documentos Google.pdf" especifica no item "1.7. Aplicativo para dispositivos móveis" da página 6, que o aplicativo móvel deverá ser desenvolvido para as plataformas Android e iOS. Para tanto, é necessário que o termo de referência também esclareça esta questão. Também é importante que sejam esclarecidas as possibilidades de desenvolvimento em plataformas híbridas (que gerem, ao fim, aplicativos para os dois sistemas operacionais).

Mauricio Lelis
Coordenação de Desenvolvimento de Negócios
Avansys Tecnologia LTDA.
CNPJ: 04.181.950/0001-10
Cel. 71 99238-5072
Tel. (71) 3617-0707
AV LUIZ TARQUINIO, 2580, SALA 302 QUADRAB000 LOTE 0003A LOT GRJ REUN CONC, PITANGUEIRAS, LAURO DE FREITAS/BA
CEP - 42.700-000

**Comment by uira** [comment]
Prezado Maurício, 

sobre as questões relacionadas ao deslocamento, entendemos que isso deve estar naturalmente contemplado nas propostas de execução de serviço, como parte do orçamento apresentado, por isso não consta no TDR. 

Sobre o aplicativo móvel, para o MVP, o requisito é o aplicativo para Android, mas as propostas podem adotar tanto as duas plataformas, quanto uma plataforma híbrida.
